#! /usr/bin/env python

#./run construct extractor1 extractor2 ... extractorN
#./run extract <path to datashard> <output file>
#./run cleanup (removes savedstate of all extractors as well as this programs')

keep_around_results_of_extractors = False #for debugging

import sys
from subprocess import call
from collections import defaultdict
import cPickle as pickle

def saveState():
    pickle.dump([extractors, num, featureMaps], open('ensemble-extractor-savedstate.pickle', 'w'))

def nextInt():
    global num
    num += 1
    return num

args = sys.argv
operation = args[1] #construct, extract, or cleanup
if operation == 'construct':
    extractors = args[2:] #space separated list of paths to extractors (folders containing run files)
    num = 0
    featureMaps = []
    for i in range(len(extractors)):
        featureMaps.append(defaultdict(nextInt))
    saveState()
    sys.exit(0)

#load saved state
extractors, num, featureMaps = pickle.load(open('ensemble-extractor-savedstate.pickle', 'r'))

if operation == 'cleanup':
    call(['rm', 'ensemble-extractor-savedstate.pickle'])
    for i in range(len(extractors)):
        call(['./'+extractors[i]+'/run', 'cleanup'])    
    sys.exit(0)

assert(operation == 'extract')
inpath = args[2] #path of datashard
outf = args[3] #output file

extractions = []
for i in range(len(extractors)):
    if call(['./'+extractors[i]+'/run', 'extract', inpath, '%s.tmp' % i]) != 0:
        print extractors[i], 'failed'
        print 'exiting'
        sys.exit(-1)
    extractions.append([x.strip().split(' ') for x in open('%s.tmp' % i, 'r').readlines()])
    if not keep_around_results_of_extractors:
        call(['rm', '%s.tmp' % i])

outf = open(outf, 'w')
for i in range(len(extractions[0])):
    outf.write('%s ' % extractions[0][i][0])
    for extraction, featureMap in zip(extractions, featureMaps):
        idxs_vals = [x.split(':') for x in extraction[i][1:]]
        outf.write('%s ' % ' '.join(['%s:%s' % (featureMap[idx], val) for idx, val in idxs_vals]))
    outf.write('\n')

outf.close()
saveState()