#! /usr/bin/env python

import sys
import util

weights = {}
legalLabels = []
learningrate=1
numupdates = 0
c = 1

def initialize():
    global legalLabels
    legalLabels = [1,]
    for l in legalLabels:
        weights[l] = util.Counter()

def classify(data):
    vectors = util.Counter()
    for l in legalLabels:
        vectors[l] = weights[l] * data
    return vectors.argMax()

def update(label, guess, data):
    global numupdates
    numupdates += 1
    global learningrate
    learningrate = float(1)/(numupdates**.5)
    if guess != label:
        if not label in legalLabels:
            legalLabels.append(label)
            weights[label] = util.Counter()
        data.divideAll(1/float(learningrate))
        tau = min(c, ((weights[guess] - weights[label]) * data + 1.0) / (2 * (data * data)))
        data.divideAll(1.0 / tau)
        weights[label] += data
        weights[guess] -= data


sys.stderr.write('Started')
line = sys.stdin.readline()
initialize()
while (line):
    features_values = line.split(" ")
    
    c = util.Counter()
    for feature, value in [(n, y.strip()) for n, y in [x.split(":") for x in features_values]]:
        c[int(feature)] = float(value)

    guess = classify(c)
    sys.stdout.write(str(guess) + "\n")
    sys.stdout.flush()

    raw_label = sys.stdin.readline().strip()

    if raw_label != "u":
        label = int(raw_label)
        update(label, guess, c)
    
    line = sys.stdin.readline()
